### ISSUE TITLE
Error running code

### ISSUE THREAD

**Issue by FormerlyChucks** [CrystalVulpine/forum#2]
When I run the `__main__.py` file, I get the following error:

`/home/dio/.local/lib/python3.7/site-packages/flask_sqlalchemy/__init__.py:834: FSADeprecationWarning: SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and will be disabled by default in the future.  Set it to True or False to suppress this warning.
  'SQLALCHEMY_TRACK_MODIFICATIONS adds significant overhead and '
Traceback (most recent call last):
  File "forum/__main__.py", line 11, in <module>
    from forum.routes import *
ModuleNotFoundError: No module named 'forum'`

Any idea how to solve?

**Comment by CrystalVulpine** [comment]
`forum` is a directory, so I'm not sure why it thinks it's a module. Make sure you are running in the directory *above* forum, which would be the root dir for this repo, where the README file is located (*not* the py files). And did you do `export PYTHONPATH=(repo_root_dir)`?

**Comment by CrystalVulpine** [comment]
Try using the full path for PYTHONPATH if it's still not working.
